services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    env_file:
      - .env
    volumes: 
      - mongo_data:/data/db
    
  
  machine-learning-client:
    build:
      context: ./machine-learning-client
    volumes:
      - ./machine-learning-client:/app
    ports:
      - "5051:5050"
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017/"
    
  chat-client:
    build:
      context: .
      dockerfile: web-app/Dockerfile
    container_name: chat-client
    env_file:
      - .env
    environment:
      - MODEL_NAME=${MODEL_NAME}
      - MODEL_MAX_NEW_TOKENS=${MODEL_MAX_NEW_TOKENS}
      - MODEL_TEMPERATURE=${MODEL_TEMPERATURE}
    command: ["python", "web-app/app.py"]
    ports:
      - "5050:5050"

volumes:
  mongo_data:
