services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    env_file:
      - .env
    volumes: 
      - mongo_data:/data/db
    
  
  machine-learning-client:
    build:
      context: ./machine-learning-client
    volumes:
      - ./machine-learning-client:/app
    ports:
      - "5051:5050"
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017/"
      MONGO_DB: "mydatabase"
    
  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: web-app
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/
      - ML_CLIENT_HOST=machine-learning-client
      - ML_CLIENT_PORT=5050
    depends_on:
      - mongo
    ports:
      - "5050:5050"

volumes:
  mongo_data:
