name: ml-client-tests
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pipenv
        run: python -m pip install --upgrade pip pipenv pytest

      - name: Build and test ML-client
        env:
          TESTING: '1'
          PYTHONPATH: ./machine-learning-client
        run: |
          cd machine-learning-client
          pipenv sync --dev --python $(which python)
          pipenv run pytest ../tests/
