name: CI ml-client-tests and coverage
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pipenv
        run: python -m pip install --upgrade pip pipenv pytest pytest-cov

      - name: Build and test ML-client
        env:
          TESTING: '1'
        run: |
          cd machine-learning-client
          pipenv install
          pipenv install pytest
          pipenv run sh -c "cd .. && python -m pytest --cov=machine-learning-client --cov-report=term --cov-report=html machine-learning-client"
          pipenv run sh -c "cd .. && python -m coverage report --fail-under=80"