name: web-app-tests
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install pipenv
        run: python -m pip install --upgrade pip pipenv pytest

      - name: Build and test web-app
        env:
          TESTING: '1'
          PYTHONPATH: ./web-app
        run: |
          cd web-app
          pipenv sync --dev --python $(which python)
          pipenv run pytest test_app.py
